# Generated by Django 5.0.1 on 2024-05-23 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_department_batch_alter_department_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='batch',
        ),
    ]
